environment:
  RUST_BACKTRACE: 1

  matrix:
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: off

test_script:
  - cargo check
  - cargo test

branches:
  only:
    - master
