[package]
name = "ptx-linker"
version = "0.6.1"
description = "NVPTX modules linker"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
repository = "https://github.com/denzp/rust-ptx-linker"
readme = "README.md"
license = "MIT"
autotests = true

exclude = [
    "tests/**/*",
]

[[bin]]
name = "ptx-linker"
doc = false
path = "src/application/main.rs"

[lib]
name = "ptx_linker"

[dependencies]
log = "0.3"
fern = "0.4"
colored = "1.5"
error-chain = "0.10"
ar = "0.5"
clap = { version = "2.31", features = ["yaml", "suggestions", "color"] }

[dependencies.llvm-sys]
version = "60"
features = ["strict-versioning"]

[dev-dependencies]
failure = "0.1"
crate-compile-test = "0.2"

[[test]]
name = "linker"
harness = false

[badges]
travis-ci = { repository = "denzp/rust-ptx-linker", branch = "master" }